# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-07-24 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0006_remove_submissionset_test_field_ro'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionset',
            name='ro_test',
            field=models.BooleanField(default=False),
        ),
    ]
