# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-07-06 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_auto_20190612_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionset',
            name='date_expiration',
            field=models.DateField(blank=True, null=True),
        ),
    ]
