# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2020-07-15 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_submissionset_date_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionset',
            name='test_field_ro',
            field=models.BooleanField(default=False),
        ),
    ]
