language: python
python:
- '2.6'
- '2.7'
install:
- pip install -r requirements.txt
- pip install -r requirements_dev.txt
script: coverage run manage.py test submissions
# after_success: coveralls
notifications:
  hipchat:
    rooms:
      secure: RJz9d4pq4Ulr3IbB1gKJ+wLr5DKBKbYIsP+nf90i5SCLqOVyirwKr4IO2R9/yFOGxs8rt36LQUR/sTPpr0cRb5vItJ2IVHmH3UZMS5jA24REuUuDlY247KXiQk7F1zlYoLi4U995+IMXGr+Wbdx4whH76erfNdMcWdPk7ZaUjbY=
  email: false
