# Access the id_github file from Secret Manager
steps:

# GKE create namespace  Namespace stars-rmq-dev
  - name: 'gcr.io/cloud-builders/gke-deploy'
    dir: 'kubernetes-manifests'
    args: ['apply', '-f', '${_GKE_NAMESPACE}', '--location=${_GKE_LOCATION}', '--cluster=${_GKE_CLUSTER}']

# Helm add repo for rabbitmq
  - name: 'gcr.io/cloud-builders/helm'
    args: ['helm', 'repo', 'add', 'bitnami', 'https://charts.bitnami.com/bitnami'] 

# Helm install for rabbitmq
  - name: 'gcr.io/cloud-builders/helm'
    args: ['helm', 'install', '${_RMQ_STATEFUL_SET}', 'bitnami/rabbitmq', '--namespace', '${_GKE_NAMESPACE}', '--set', 'auth.password=$(gcloud secrets versions access latest --secret=${_SECRET_NAME})'] 