# Access the id_github file from Secret Manager
steps:

# GKE create namespace  Namespace stars-rmq-dev
  - name: 'gcr.io/cloud-builders/gke-deploy'
    dir: 'kubernetes-manifests'
    args: ['apply', '-f', '${_GKE_NAMESPACE_YAML}', '--location=${_GKE_LOCATION}', '--cluster=${_GKE_CLUSTER}']

# Helm add repo for rabbitmq
  - name: 'gcr.io/aashe-migration/helm'
    args: ['repo', 'add', 'bitnami', 'https://charts.bitnami.com/bitnami'] 

# Helm install of rabbitmq
  - name: 'gcr.io/aashe-migration/helm'
    entrypoint: 'bash'
    args:
    - '-c'
    - 'if [ ${_DELETE_RABBITMQ} = "yes" ]'
    - 'then'
    - |
      SECRET=$(gcloud secrets versions access latest --secret=${_RMQ_PWD_SECRET})
      echo $SECRET
      helm uninstall ${_RMQ_NAME} bitnami/rabbitmq --namespace ${_GKE_NAMESPACE}
    - fi'