# Access the id_github file from Secret Manager
steps:

# Access the secrets file from Secret Manager
  - id: load kubernetes secrets file
    name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      mkdir /workspace/kubernetes-manifests/${_KUST_BUILD_DIR}/secrets
      gcloud secrets versions access latest --secret=${_KUST_SECRET_FILE} > /workspace/kubernetes-manifests/${_KUST_BUILD_DIR}/secrets/kustomization.yaml

# Kustomize builds kubernetes yaml and kubectl deploys
  - id: deploy certificate issuer and stars certificates
    name: 'gcr.io/$PROJECT_ID/kustomize:${_KUSTOMIZE_VERSION}'
    dir: 'kubernetes-manifests'
    args:
    - 'build'
    - '${_KUST_BUILD_DIR}'
    env:
      - 'APPLY=true'
      - 'CLOUDSDK_COMPUTE_ZONE=${_GKE_LOCATION}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}'
      - 'GCLOUD_PROJECT=$PROJECT_ID'