# Access the id_github file from Secret Manager
steps:
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash'
    args: [ '-c', 'gcloud secrets versions access latest --secret=github_dspeck > /root/.ssh/id_github' ]
    volumes:
    - name: 'ssh'
      path: /root/.ssh

# Set up git with key and domain
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      chmod 600 /root/.ssh/id_github
      cat <<EOF >/root/.ssh/config
      Hostname github.com
      IdentityFile /root/.ssh/id_github
      EOF
      ssh-keyscan -t rsa github.com > /root/.ssh/known_hosts
    volumes:
    - name: 'ssh'
      path: /root/.ssh
      
# Connect to the repository
  - name: 'gcr.io/cloud-builders/git'
    args:
    - clone
    - --recurse-submodules
    - git@github.com:dspeck1/AASHE/django-celery-downloader.git@no-dj-celery
    volumes:
    - name: 'ssh'
      path: /root/.ssh

# Docker build
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'src'
    args: ['build', '-t', 'gcr.io/aashe-migration/stars-image:$BUILD_ID', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/aashe-migration/stars-image:$BUILD_ID']