version: "3.7"

services:

  mysql:
    image: mysql:5.7.28
    volumes:
      - /var/lib/mysql/data/
    ports:
      - "3306:3306"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=123456

  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    environment:
      - STARS_DB_URL=mysql://root:123456@mysql:3306/stars
      - MEDIA_ROOT=/usr/media
      - STATIC_ROOT=/usr/static
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - mysql

  rabbitmq:
    image: rabbitmq:3.8.1

  worker:
    build: ./
    command: celery worker -A stars -l info
    volumes:
      - ./:/usr/src/app/
      - temp:/tmp
    env_file:
      - ./.env.dev
    environment:
      - STARS_DB_URL=mysql://root:123456@mysql:3306/stars
      - MEDIA_ROOT=/usr/media
      - STATIC_ROOT=/usr/static
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672/

  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - /usr/src/app/
      - temp:/tmp
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    environment:
      - STARS_DB_URL=mysql://root:123456@mysql:3306/stars
      - MEDIA_ROOT=/usr/media
      - STATIC_ROOT=/usr/static
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - mysql
      - rabbitmq

volumes:
  temp:
