apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeAddress
metadata:
  name: sqlinstance-private-ip
  namespace: admin-config-conn
spec:
  addressType: INTERNAL
  location: global
  purpose: VPC_PEERING
  prefixLength: 16
  networkRef:
    name: sqlinstance-private-ip
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetwork
metadata:
  name: sqlinstance-private-ip
  namespace: admin-config-conn
spec:
  autoCreateSubnetworks: false
---
apiVersion: servicenetworking.cnrm.cloud.google.com/v1beta1
kind: ServiceNetworkingConnection
metadata:
  name: sqlinstance-private-ip
  namespace: admin-config-conn
spec:
  networkRef:
    name: sqlinstance-private-ip
    namespace: admin-config-conn
  reservedPeeringRanges:
    - name: sqlinstance-private-ip
  service: servicenetworking.googleapis.com
---
apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  name: resourcemanager.googleapis.com
  namespace: admin-config-conn
---
apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  name: servicenetworking.googleapis.com
  namespace: admin-config-conn