apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: stars-http-hc-config
  namespace: stars-dev
spec:
  healthCheck:
    checkIntervalSec: 15
    port: 8080
    type: HTTP
    requestPath: /