apiVersion: apps/v1
kind: Deployment
metadata:
  name: stars
  labels:
    app: stars
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stars
      tier: app
  template:
    metadata:
      labels:
        app: stars
        tier: app
    spec:
      containers:
      - name: stars
        image: gcr.io/aashe-migration/stars-image:BUILD_ID
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: EMAIL_HOST_PASSWORD
          value: "oridianybder"
        - name: STARS_DB_URL
          value: mysql://root:123456@127.0.0.1:3306/stars
        - name: ISS_DB_URL
          value: mysql://root@localhost/iss
        - name: MS_ACCESS_KEY
          value: "AAAAAPIAF8qMCQs8Vb1AGA"
        - name: MS_SECRET_KEY
          value: blah
        - name: MS_ASSOCIATION_ID
          value: "6faf90e4-0004-c3a4-9500-0b3b58a242ba"
        - name: STARS_BROCHURE_HOST
          value: aashestars.wpengine.com
        - name: STARS_REPORTS_HOST
          value: localhost:8000
        - name: STARS_BENCHMARKS_HOST
          value: benchmarks.aashe.org
        - name: STARS_MS_PUBLICATION_ID
          value: blah
        - name: EMAIL_REPLY_TO
          value: blah
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
