version: "3.7"

services:
  mysql:
    image: mysql:5.7.28
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - my-datavolume:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=stars

  rabbitmq:
    image: rabbitmq:3.8.1

  web:
    build: ../
    image: django
    command: python manage.py runserver 0.0.0.0:8000
    # command:
    #   [
    #     "./wait-for-it.sh",
    #     "mysql:3306",
    #     "--",
    #     "python manage.py runserver 0.0.0.0:8000",
    #   ]
    volumes:
      - ../:/usr/src/app/
      - ./bin:/usr/src/app/bin
      - temp:/tmp
      - static:/usr/static
    ports:
      - 8000:8000
    env_file:
      - ../.env.dev
    environment:
      - STARS_DB_URL=mysql://root:123456@mysql:3306/stars
      - MEDIA_ROOT=/usr/media
      - STATIC_ROOT=/usr/static
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672/
      - STARS_TEST_DB=sqlite:///~/sqlite/stars_tests.db
    depends_on:
      - mysql
      - rabbitmq

  # migration:
  #   image: django
  #   command: python manage.py migrate --noinput
  #   env_file:
  #     - ../.env.dev
  #   environment:
  #     - STARS_DB_URL=mysql://root:123456@mysql:3306/stars
  #     - MEDIA_ROOT=/usr/media
  #     - STATIC_ROOT=/usr/static
  #     - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672/
  #     - STARS_TEST_DB=sqlite:///~/sqlite/stars_tests.db
  #   depends_on:
  #     - mysql

  worker:
    image: django
    command: celery worker -A stars -l info
    volumes:
      - ../:/usr/src/app/
      - temp:/tmp
      - static:/usr/static
    env_file:
      - ../.env.dev
    environment:
      - STARS_DB_URL=mysql://root:123456@mysql:3306/stars
      - MEDIA_ROOT=/usr/media
      - STATIC_ROOT=/usr/static
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672/
      - STARS_TEST_DB=sqlite:///~/sqlite/stars_tests.db
    depends_on:
      - mysql
      - rabbitmq

volumes:
  temp:
  static:
  my-datavolume:
