apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    email: devops@aashe.org
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: stars-issuer-account-key
    solvers:
    - dns01:
        cloudflare:
          email: it@aashe.org
          apiTokenSecretRef:
            name: cloudflare-api-token-secret-7mtdhkcmdb
            key: api-token
      selector:
        dnsZones:
        - 'aashe.org'